// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	TaskDetails          string   `protobuf:"bytes,2,opt,name=taskDetails,proto3" json:"taskDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Task) GetTaskDetails() string {
	if m != nil {
		return m.TaskDetails
	}
	return ""
}

type TaskUpdate struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	UpdateDetails        string   `protobuf:"bytes,2,opt,name=updateDetails,proto3" json:"updateDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskUpdate) Reset()         { *m = TaskUpdate{} }
func (m *TaskUpdate) String() string { return proto.CompactTextString(m) }
func (*TaskUpdate) ProtoMessage()    {}
func (*TaskUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{1}
}

func (m *TaskUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskUpdate.Unmarshal(m, b)
}
func (m *TaskUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskUpdate.Marshal(b, m, deterministic)
}
func (m *TaskUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskUpdate.Merge(m, src)
}
func (m *TaskUpdate) XXX_Size() int {
	return xxx_messageInfo_TaskUpdate.Size(m)
}
func (m *TaskUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_TaskUpdate proto.InternalMessageInfo

func (m *TaskUpdate) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskUpdate) GetUpdateDetails() string {
	if m != nil {
		return m.UpdateDetails
	}
	return ""
}

type Request struct {
	Action               string   `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

type Response struct {
	Data                 string   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_0c843d59d2d938e7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "core.Task")
	proto.RegisterType((*TaskUpdate)(nil), "core.TaskUpdate")
	proto.RegisterType((*Request)(nil), "core.Request")
	proto.RegisterType((*Response)(nil), "core.Response")
}

func init() {
	proto.RegisterFile("node.proto", fileDescriptor_0c843d59d2d938e7)
}

var fileDescriptor_0c843d59d2d938e7 = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x4b, 0xeb, 0x40,
	0x14, 0x25, 0x8f, 0xd0, 0xd7, 0x77, 0x4b, 0x9f, 0x65, 0x16, 0x52, 0x5d, 0x48, 0x0d, 0x2e, 0xc4,
	0x8f, 0x10, 0xad, 0x2b, 0xdd, 0x58, 0xab, 0xd4, 0x8a, 0x88, 0xb4, 0xba, 0x71, 0x37, 0x66, 0xae,
	0x35, 0x34, 0xce, 0xc4, 0x99, 0x1b, 0xfd, 0x5f, 0xfe, 0x42, 0x99, 0x49, 0x8a, 0xb6, 0xa0, 0xcd,
	0x6e, 0xce, 0x99, 0xf3, 0x31, 0xf7, 0x86, 0x00, 0x48, 0x25, 0x30, 0xcc, 0xb4, 0x22, 0xc5, 0xfc,
	0x58, 0x69, 0x0c, 0x4e, 0xc1, 0xbf, 0xe3, 0x66, 0xca, 0x56, 0xa1, 0x46, 0xdc, 0x4c, 0x87, 0xa2,
	0xed, 0x75, 0xbc, 0xed, 0x7f, 0xa3, 0x12, 0xb1, 0x0e, 0x34, 0xec, 0xe9, 0x1c, 0x89, 0x27, 0xa9,
	0x69, 0xff, 0x71, 0x97, 0xdf, 0xa9, 0xe0, 0x0a, 0xc0, 0x26, 0xdc, 0x67, 0x82, 0x13, 0xfe, 0x98,
	0xb3, 0x05, 0xcd, 0xdc, 0x29, 0xe6, 0x93, 0xe6, 0xc9, 0x60, 0x13, 0xfe, 0x8e, 0xf0, 0x35, 0x47,
	0x43, 0x36, 0x88, 0xc7, 0x94, 0x28, 0x39, 0x0b, 0x2a, 0x50, 0xb0, 0x01, 0xf5, 0x11, 0x9a, 0x4c,
	0x49, 0x83, 0x8c, 0x81, 0x2f, 0x38, 0xf1, 0x52, 0xe1, 0xce, 0x87, 0x1f, 0x3e, 0x34, 0x6e, 0x94,
	0xc0, 0x31, 0xea, 0xb7, 0x24, 0x46, 0xb6, 0x07, 0x8d, 0x01, 0x92, 0x65, 0x86, 0xf2, 0x49, 0xb1,
	0x66, 0x68, 0xc7, 0x0e, 0xcb, 0x96, 0xf5, 0xff, 0x33, 0x58, 0x26, 0x1e, 0x40, 0xab, 0x97, 0xd3,
	0x33, 0x4a, 0x4a, 0x62, 0x4e, 0x68, 0x6d, 0x15, 0x2c, 0xc5, 0xec, 0xae, 0x95, 0x38, 0xe5, 0x66,
	0x99, 0x65, 0x1f, 0xa0, 0x67, 0x4c, 0x32, 0x91, 0x6e, 0xf5, 0xbf, 0x8b, 0x23, 0x8f, 0x75, 0x67,
	0x0d, 0x56, 0x5e, 0xa9, 0x21, 0xf2, 0x58, 0x08, 0xcd, 0x01, 0x52, 0x65, 0x07, 0xdb, 0x05, 0xe8,
	0x73, 0x19, 0x63, 0x5a, 0xe1, 0x4d, 0x6c, 0xc7, 0x2d, 0xd5, 0x2a, 0xaf, 0x13, 0x43, 0x8b, 0x6a,
	0x28, 0xa0, 0xbd, 0x8e, 0x3c, 0x76, 0x0c, 0x6b, 0xbd, 0x78, 0x2a, 0xd5, 0x7b, 0x8a, 0x62, 0xe2,
	0x46, 0xe8, 0xab, 0x97, 0x2c, 0x45, 0xfb, 0x35, 0x97, 0xf5, 0x44, 0xb0, 0x72, 0xc9, 0xa5, 0x48,
	0x9d, 0xed, 0x42, 0x6b, 0xa5, 0x97, 0x39, 0x8e, 0xa0, 0x35, 0x46, 0x29, 0xac, 0xfe, 0x56, 0xab,
	0x89, 0x46, 0x63, 0x58, 0xeb, 0xeb, 0x3d, 0xc5, 0x1e, 0x17, 0x5d, 0x67, 0xf5, 0x87, 0x5a, 0x78,
	0x62, 0xa9, 0xc7, 0x9a, 0xfb, 0x39, 0xba, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0xd4, 0xb2,
	0xda, 0x2a, 0x03, 0x00, 0x00,
}
